package xxup.oracle.apps.per.publicservice.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerPositionsVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public PerPositionsVOImpl() {
    }
        
    public void initPosVO(String personId){
        setWhereClauseParams(null);
        setWhereClause("person_id = :1");
        setWhereClauseParam(0, personId);
        executeQuery();
    }


}
