package xxup.oracle.apps.per.publicservice.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.Row;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerPSAttachmentsVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public PerPSAttachmentsVOImpl() {
    }
    
    
    public void getAttachments(String sequenceNo) {
        setWhereClauseParams(null);
        setWhereClause("sequence_no = :1");
        setWhereClauseParam(0, sequenceNo);
        executeQuery();
    }
    
    public void initNewAttachment() {
        setMaxFetchSize(0);
        Row row = createRow();
        insertRow(row);
        executeQuery();
    }
    
}
