package xxup.oracle.apps.per.publicservice.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerPSActionHistoryVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public PerPSActionHistoryVOImpl() {
    }

    public void initApprovers(String sequenceNo) {
        //setMaxFetchSize(0);
    
        setWhereClauseParams(null);
        setWhereClause("sequence_no = :1");
        setWhereClauseParam(0, sequenceNo);
        executeQuery();
    }
}
