package xxup.oracle.apps.per.publicservice.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxupPerPSApprovedVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxupPerPSApprovedVOImpl() {
    }
    
    public void showSummaryVO() {
        setWhereClause(null);
        setWhereClause("person_id = fnd_global.employee_id");
        executeQuery();
        
    }
    
}
