package xxup.oracle.apps.per.publicservice.server.tr;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.Row;

import xxup.oracle.apps.per.publicservice.server.XxupPerPublicServiceHeaderEOVOImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxupPerPSHeaderTrEOVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxupPerPSHeaderTrEOVOImpl() {
    }


    public void initExistingPS(String sequenceNumber) {
        setWhereClauseParams(null);
        setWhereClause("sequence_no = :1");
        setWhereClauseParam(0, sequenceNumber);
        executeQuery();
    }

    //updated method to get transactional record
    public void initTranPS(String itemKey) {
        setWhereClauseParams(null);
        setWhereClause("item_key = :1");
        setWhereClauseParam(0, itemKey);
        executeQuery();
    }

     public void initNewRecord() {
     
        setMaxFetchSize(0);
        executeQuery();
        Row row = createRow();
        insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);

    }
    
    
    // public void initUpdateRecord(String sequenceNumber) {
    //     XxupPerPublicServiceHeaderEOVOImpl mainVO =
    //         new XxupPerPublicServiceHeaderEOVOImpl();
        
    //     Row mainRow = null;
    //     if(mainVO != null){
    //         mainVO.setWhereClauseParams(null);
    //         mainVO.setWhereClause("sequence_no = :1");
    //         mainVO.setWhereClauseParam(0, sequenceNumber);
    //         mainVO.executeQuery();
            
    //         mainRow = mainVO.getCurrentRow();
    //     }
        
        
    
    //     Row row = createRow();
    //     insertRow(mainRow);
    //     row.setNewRowState(Row.STATUS_INITIALIZED);

    // }
}
