package xxup.oracle.apps.per.publicservice.schema.server;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxupPerPublicServiceHeaderEOImpl extends OAEntityImpl {
    public static final int SEQUENCENO = 0;
    public static final int POSITIONID = 1;
    public static final int PROJECTNAME = 2;
    public static final int PRIMARYROLE = 3;
    public static final int PROJECTTYPE = 4;
    public static final int REQUESTDATE = 5;
    public static final int RESPONDEDDATE = 6;
    public static final int STARTDATE = 7;
    public static final int ENDDATE = 8;
    public static final int DURATIONHOURS = 9;
    public static final int SOURCEOFFUND = 10;
    public static final int COSTOFPARTICIPATION = 11;
    public static final int PARTNERORGORINST = 12;
    public static final int BENEFICIARYCATEGORY = 13;
    public static final int TYPEOFBENEFICIARY = 14;
    public static final int UNITOFBENEFICIARY = 15;
    public static final int NOOFBENEFICIARY = 16;
    public static final int POSTACTEVALRATING = 17;
    public static final int REMARKS = 18;
    public static final int ATTRIBUTE1 = 19;
    public static final int ATTRIBUTE2 = 20;
    public static final int ATTRIBUTE3 = 21;
    public static final int ATTRIBUTE4 = 22;
    public static final int ATTRIBUTE5 = 23;
    public static final int LASTUPDATEDATE = 24;
    public static final int LASTUPDATEDBY = 25;
    public static final int LASTUPDATELOGIN = 26;
    public static final int CREATEDBY = 27;
    public static final int CREATIONDATE = 28;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxupPerPublicServiceHeaderEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxup.oracle.apps.per.publicservice.schema.server.XxupPerPublicServiceHeaderEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for SequenceNo, using the alias name SequenceNo
     */
    public Number getSequenceNo() {
        return (Number)getAttributeInternal(SEQUENCENO);
    }

    /**Sets <code>value</code> as the attribute value for SequenceNo
     */
    public void setSequenceNo(Number value) {
        setAttributeInternal(SEQUENCENO, value);
    }

    /**Gets the attribute value for PositionId, using the alias name PositionId
     */
    public Number getPositionId() {
        return (Number)getAttributeInternal(POSITIONID);
    }

    /**Sets <code>value</code> as the attribute value for PositionId
     */
    public void setPositionId(Number value) {
        setAttributeInternal(POSITIONID, value);
    }

    /**Gets the attribute value for ProjectName, using the alias name ProjectName
     */
    public String getProjectName() {
        return (String)getAttributeInternal(PROJECTNAME);
    }

    /**Sets <code>value</code> as the attribute value for ProjectName
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**Gets the attribute value for PrimaryRole, using the alias name PrimaryRole
     */
    public String getPrimaryRole() {
        return (String)getAttributeInternal(PRIMARYROLE);
    }

    /**Sets <code>value</code> as the attribute value for PrimaryRole
     */
    public void setPrimaryRole(String value) {
        setAttributeInternal(PRIMARYROLE, value);
    }

    /**Gets the attribute value for RequestDate, using the alias name RequestDate
     */
    public Date getRequestDate() {
        return (Date)getAttributeInternal(REQUESTDATE);
    }

    /**Sets <code>value</code> as the attribute value for RequestDate
     */
    public void setRequestDate(Date value) {
        setAttributeInternal(REQUESTDATE, value);
    }

    /**Gets the attribute value for RespondedDate, using the alias name RespondedDate
     */
    public Date getRespondedDate() {
        return (Date)getAttributeInternal(RESPONDEDDATE);
    }

    /**Sets <code>value</code> as the attribute value for RespondedDate
     */
    public void setRespondedDate(Date value) {
        setAttributeInternal(RESPONDEDDATE, value);
    }

    /**Gets the attribute value for StartDate, using the alias name StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**Gets the attribute value for EndDate, using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**Gets the attribute value for DurationHours, using the alias name DurationHours
     */
    public Number getDurationHours() {
        return (Number)getAttributeInternal(DURATIONHOURS);
    }

    /**Sets <code>value</code> as the attribute value for DurationHours
     */
    public void setDurationHours(Number value) {
        setAttributeInternal(DURATIONHOURS, value);
    }


    /**Gets the attribute value for SourceOfFund, using the alias name SourceOfFund
     */
    public String getSourceOfFund() {
        return (String)getAttributeInternal(SOURCEOFFUND);
    }

    /**Sets <code>value</code> as the attribute value for SourceOfFund
     */
    public void setSourceOfFund(String value) {
        setAttributeInternal(SOURCEOFFUND, value);
    }

    /**Gets the attribute value for CostOfParticipation, using the alias name CostOfParticipation
     */
    public String getCostOfParticipation() {
        return (String)getAttributeInternal(COSTOFPARTICIPATION);
    }

    /**Sets <code>value</code> as the attribute value for CostOfParticipation
     */
    public void setCostOfParticipation(String value) {
        setAttributeInternal(COSTOFPARTICIPATION, value);
    }

    /**Gets the attribute value for PartnerOrgOrInst, using the alias name PartnerOrgOrInst
     */
    public String getPartnerOrgOrInst() {
        return (String)getAttributeInternal(PARTNERORGORINST);
    }

    /**Sets <code>value</code> as the attribute value for PartnerOrgOrInst
     */
    public void setPartnerOrgOrInst(String value) {
        setAttributeInternal(PARTNERORGORINST, value);
    }

    /**Gets the attribute value for BeneficiaryCategory, using the alias name BeneficiaryCategory
     */
    public String getBeneficiaryCategory() {
        return (String)getAttributeInternal(BENEFICIARYCATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for BeneficiaryCategory
     */
    public void setBeneficiaryCategory(String value) {
        setAttributeInternal(BENEFICIARYCATEGORY, value);
    }


    /**Gets the attribute value for NoOfBeneficiary, using the alias name NoOfBeneficiary
     */
    public Number getNoOfBeneficiary() {
        return (Number)getAttributeInternal(NOOFBENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for NoOfBeneficiary
     */
    public void setNoOfBeneficiary(Number value) {
        setAttributeInternal(NOOFBENEFICIARY, value);
    }


    /**Gets the attribute value for PostActEvalRating, using the alias name PostActEvalRating
     */
    public String getPostActEvalRating() {
        return (String)getAttributeInternal(POSTACTEVALRATING);
    }

    /**Sets <code>value</code> as the attribute value for PostActEvalRating
     */
    public void setPostActEvalRating(String value) {
        setAttributeInternal(POSTACTEVALRATING, value);
    }

    /**Gets the attribute value for Remarks, using the alias name Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**Sets <code>value</code> as the attribute value for Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }


    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SEQUENCENO:
            return getSequenceNo();
        case POSITIONID:
            return getPositionId();
        case PROJECTNAME:
            return getProjectName();
        case PRIMARYROLE:
            return getPrimaryRole();
        case PROJECTTYPE:
            return getProjectType();
        case REQUESTDATE:
            return getRequestDate();
        case RESPONDEDDATE:
            return getRespondedDate();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case DURATIONHOURS:
            return getDurationHours();
        case SOURCEOFFUND:
            return getSourceOfFund();
        case COSTOFPARTICIPATION:
            return getCostOfParticipation();
        case PARTNERORGORINST:
            return getPartnerOrgOrInst();
        case BENEFICIARYCATEGORY:
            return getBeneficiaryCategory();
        case TYPEOFBENEFICIARY:
            return getTypeOfBeneficiary();
        case UNITOFBENEFICIARY:
            return getUnitOfBeneficiary();
        case NOOFBENEFICIARY:
            return getNoOfBeneficiary();
        case POSTACTEVALRATING:
            return getPostActEvalRating();
        case REMARKS:
            return getRemarks();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SEQUENCENO:
            setSequenceNo((Number)value);
            return;
        case POSITIONID:
            setPositionId((Number)value);
            return;
        case PROJECTNAME:
            setProjectName((String)value);
            return;
        case PRIMARYROLE:
            setPrimaryRole((String)value);
            return;
        case PROJECTTYPE:
            setProjectType((String)value);
            return;
        case REQUESTDATE:
            setRequestDate((Date)value);
            return;
        case RESPONDEDDATE:
            setRespondedDate((Date)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case DURATIONHOURS:
            setDurationHours((Number)value);
            return;
        case SOURCEOFFUND:
            setSourceOfFund((String)value);
            return;
        case COSTOFPARTICIPATION:
            setCostOfParticipation((String)value);
            return;
        case PARTNERORGORINST:
            setPartnerOrgOrInst((String)value);
            return;
        case BENEFICIARYCATEGORY:
            setBeneficiaryCategory((String)value);
            return;
        case TYPEOFBENEFICIARY:
            setTypeOfBeneficiary((String)value);
            return;
        case UNITOFBENEFICIARY:
            setUnitOfBeneficiary((String)value);
            return;
        case NOOFBENEFICIARY:
            setNoOfBeneficiary((Number)value);
            return;
        case POSTACTEVALRATING:
            setPostActEvalRating((String)value);
            return;
        case REMARKS:
            setRemarks((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
        if (getSequenceNo() == null) {
            OADBTransaction tr = getOADBTransaction();
            setSequenceNo(tr.getSequenceValue("XXUP.XXUP_PER_PUBLIC_SERVICE_SEQ"));
        }
    }


    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Gets the attribute value for ProjectType, using the alias name ProjectType
     */
    public String getProjectType() {
        return (String)getAttributeInternal(PROJECTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for ProjectType
     */
    public void setProjectType(String value) {
        setAttributeInternal(PROJECTTYPE, value);
    }

    /**Gets the attribute value for TypeOfBeneficiary, using the alias name TypeOfBeneficiary
     */
    public String getTypeOfBeneficiary() {
        return (String)getAttributeInternal(TYPEOFBENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for TypeOfBeneficiary
     */
    public void setTypeOfBeneficiary(String value) {
        setAttributeInternal(TYPEOFBENEFICIARY, value);
    }

    /**Gets the attribute value for UnitOfBeneficiary, using the alias name UnitOfBeneficiary
     */
    public String getUnitOfBeneficiary() {
        return (String)getAttributeInternal(UNITOFBENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for UnitOfBeneficiary
     */
    public void setUnitOfBeneficiary(String value) {
        setAttributeInternal(UNITOFBENEFICIARY, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number sequenceNo) {
        return new Key(new Object[]{sequenceNo});
    }
}
