package xxup.oracle.apps.per.publicservice.institutional.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerPSInstActivitiesVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public PerPSInstActivitiesVOImpl() {
    }
    
    public void initRecords(){
        setWhereClause(null);
        setOrderByClause("CASE WHEN ACTIVITY = 'Others' THEN 1 END");
        executeQuery();
    }
}
