package xxup.oracle.apps.per.publicservice.institutional.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import xxup.oracle.apps.per.publicservice.lov.server.PerPSSubjectAreaInterestVOImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PSInstitutionalLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public PSInstitutionalLovAMImpl() {
    }

    /**Container's getter for PerPSInstCUVO1
     */
    public PerPSInstCUVOImpl getPerPSInstCUVO1() {
        return (PerPSInstCUVOImpl)findViewObject("PerPSInstCUVO1");
    }
    
    public void initCUVO(String pPersonId){
        PerPSInstCUVOImpl posVO = getPerPSInstCUVO1();
        
        posVO.initVO(pPersonId);
    }
    
    

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxup.oracle.apps.per.publicservice.institutional.lov.server", /* package name */
      "PSInstitutionalLovAMLocal" /* Configuration Name */);
    }

    /**Container's getter for PerPSInstMemberVO1
     */
    public PerPSInstMemberVOImpl getPerPSInstMemberVO1() {
        return (PerPSInstMemberVOImpl)findViewObject("PerPSInstMemberVO1");
    }

    /**Container's getter for PerPSSubjectAreaInterestVO1
     */
    public PerPSSubjectAreaInterestVOImpl getPerPSSubjectAreaInterestVO1() {
        return (PerPSSubjectAreaInterestVOImpl)findViewObject("PerPSSubjectAreaInterestVO1");
    }

    /**Container's getter for PerPSInstOrganizationsVO1
     */
    public PerPSInstOrganizationsVOImpl getPerPSInstOrganizationsVO1() {
        return (PerPSInstOrganizationsVOImpl)findViewObject("PerPSInstOrganizationsVO1");
    }
}
