package xxup.oracle.apps.per.publicservice.institutional.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PerPSInstAdminSummaryVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public PerPSInstAdminSummaryVOImpl() {
    }

    protected static final int ALL_LEVEL = 0;
    protected static final int USER_LEVEL = 1;
    protected static final int UNIT_LEVEL = 2;
    protected static final int CU_LEVEL = 3;


    public void showSummaryVO(int accessLevel) {

    	switch(accessLevel){
    		case USER_LEVEL:
    			System.out.println(USER_LEVEL);
    			this.execWhereClause();
    			break;
    		case UNIT_LEVEL:
    			System.out.println(UNIT_LEVEL);
    			break;
    		case ALL_LEVEL:
    			System.out.println(ALL_LEVEL);
    			break;
    		case CU_LEVEL:
    			System.out.println(CU_LEVEL);
    			break;
    		default:
    			System.out.println("none");
    	}
    }


    void execWhereClause(){
    	setWhereClause(null);
//        setWhereClause("person_id = fnd_global.employee_id");
        executeQuery();
    }
}
