package xxup.oracle.apps.per.publicservice.institutional.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxupPerPSInstBenefTypeEOVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxupPerPSInstBenefTypeEOVOImpl() {
    }
    
    
    public void initExistingPS(String sequenceNumber) {
        setWhereClauseParams(null);
        setWhereClause("sequence_no = :1");
        setWhereClauseParam(0, sequenceNumber);
        setOrderByClause("TYPE_OF_BENEFICIARY");  
        executeQuery();
    }

     public void initNewRecord() {
         
        setMaxFetchSize(0);
        setOrderByClause("TYPE_OF_BENEFICIARY");  
        executeQuery();
    //        Row row = createRow();
    //        insertRow(row);
    //        row.setNewRowState(Row.STATUS_INITIALIZED);
        

    }
}
