package xxup.oracle.apps.per.publicservice.institutional.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxupPerPSInstitutionalEOVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxupPerPSInstitutionalEOVOImpl() {
    }
    
    public void showSummaryVO(){
        setWhereClause(null);
        setWhereClause("created_by = fnd_global.user_id");
        setOrderByClause("project_name");
        executeQuery();
        
        
    
    }
}
