package xxup.oracle.apps.per.publicservice.institutional.schema.server.tr;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxupPerPsInstitutionalTrEOImpl extends OAEntityImpl {
    public static final int SEQUENCENO = 0;
    public static final int CONSTITUENTUNIVERSITY = 1;
    public static final int PROJECTNAME = 2;
    public static final int IMPLEMENTATIONSTARTDATE = 3;
    public static final int IMPLEMENTATIONENDDATE = 4;
    public static final int DURATION = 5;
    public static final int DURATIONUNIT = 6;
    public static final int IMPLEMENTATIONFREQUENCY = 7;
    public static final int FUNDINGAGENCY = 8;
    public static final int COSTOFPARTICIPATION = 9;
    public static final int UNITOFBENEFICIARY = 10;
    public static final int NOOFBENEFICIARY = 11;
    public static final int POSTACTEVALRATING = 12;
    public static final int REMARKS = 13;
    public static final int REQUESTSTATUS = 14;
    public static final int ATTRIBUTE1 = 15;
    public static final int ATTRIBUTE2 = 16;
    public static final int ATTRIBUTE3 = 17;
    public static final int ATTRIBUTE4 = 18;
    public static final int ATTRIBUTE5 = 19;
    public static final int LASTUPDATEDATE = 20;
    public static final int LASTUPDATEDBY = 21;
    public static final int LASTUPDATELOGIN = 22;
    public static final int CREATEDBY = 23;
    public static final int CREATIONDATE = 24;
    public static final int ITEMKEY = 25;
    public static final int STATUS = 26;
    public static final int MALEBENEFCOUNT = 27;
    public static final int FEMALEBENEFCOUNT = 28;
    public static final int PROJECTLEADER = 29;
    public static final int ROWID = 30;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxupPerPsInstitutionalTrEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxup.oracle.apps.per.publicservice.institutional.schema.server.tr.XxupPerPsInstitutionalTrEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for SequenceNo, using the alias name SequenceNo
     */
    public Number getSequenceNo() {
        return (Number)getAttributeInternal(SEQUENCENO);
    }

    /**Sets <code>value</code> as the attribute value for SequenceNo
     */
    public void setSequenceNo(Number value) {
        setAttributeInternal(SEQUENCENO, value);
    }

    /**Gets the attribute value for ConstituentUniversity, using the alias name ConstituentUniversity
     */
    public String getConstituentUniversity() {
        return (String)getAttributeInternal(CONSTITUENTUNIVERSITY);
    }

    /**Sets <code>value</code> as the attribute value for ConstituentUniversity
     */
    public void setConstituentUniversity(String value) {
        setAttributeInternal(CONSTITUENTUNIVERSITY, value);
    }

    /**Gets the attribute value for ProjectName, using the alias name ProjectName
     */
    public String getProjectName() {
        return (String)getAttributeInternal(PROJECTNAME);
    }

    /**Sets <code>value</code> as the attribute value for ProjectName
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**Gets the attribute value for ImplementationStartDate, using the alias name ImplementationStartDate
     */
    public Date getImplementationStartDate() {
        return (Date)getAttributeInternal(IMPLEMENTATIONSTARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for ImplementationStartDate
     */
    public void setImplementationStartDate(Date value) {
        setAttributeInternal(IMPLEMENTATIONSTARTDATE, value);
    }

    /**Gets the attribute value for ImplementationEndDate, using the alias name ImplementationEndDate
     */
    public Date getImplementationEndDate() {
        return (Date)getAttributeInternal(IMPLEMENTATIONENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for ImplementationEndDate
     */
    public void setImplementationEndDate(Date value) {
        setAttributeInternal(IMPLEMENTATIONENDDATE, value);
    }

    /**Gets the attribute value for Duration, using the alias name Duration
     */
    public Number getDuration() {
        return (Number)getAttributeInternal(DURATION);
    }

    /**Sets <code>value</code> as the attribute value for Duration
     */
    public void setDuration(Number value) {
        setAttributeInternal(DURATION, value);
    }

    /**Gets the attribute value for DurationUnit, using the alias name DurationUnit
     */
    public String getDurationUnit() {
        return (String)getAttributeInternal(DURATIONUNIT);
    }

    /**Sets <code>value</code> as the attribute value for DurationUnit
     */
    public void setDurationUnit(String value) {
        setAttributeInternal(DURATIONUNIT, value);
    }

    /**Gets the attribute value for ImplementationFrequency, using the alias name ImplementationFrequency
     */
    public String getImplementationFrequency() {
        return (String)getAttributeInternal(IMPLEMENTATIONFREQUENCY);
    }

    /**Sets <code>value</code> as the attribute value for ImplementationFrequency
     */
    public void setImplementationFrequency(String value) {
        setAttributeInternal(IMPLEMENTATIONFREQUENCY, value);
    }

    /**Gets the attribute value for FundingAgency, using the alias name FundingAgency
     */
    public String getFundingAgency() {
        return (String)getAttributeInternal(FUNDINGAGENCY);
    }

    /**Sets <code>value</code> as the attribute value for FundingAgency
     */
    public void setFundingAgency(String value) {
        setAttributeInternal(FUNDINGAGENCY, value);
    }

    /**Gets the attribute value for CostOfParticipation, using the alias name CostOfParticipation
     */
    public String getCostOfParticipation() {
        return (String)getAttributeInternal(COSTOFPARTICIPATION);
    }

    /**Sets <code>value</code> as the attribute value for CostOfParticipation
     */
    public void setCostOfParticipation(String value) {
        setAttributeInternal(COSTOFPARTICIPATION, value);
    }

    /**Gets the attribute value for UnitOfBeneficiary, using the alias name UnitOfBeneficiary
     */
    public String getUnitOfBeneficiary() {
        return (String)getAttributeInternal(UNITOFBENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for UnitOfBeneficiary
     */
    public void setUnitOfBeneficiary(String value) {
        setAttributeInternal(UNITOFBENEFICIARY, value);
    }

    /**Gets the attribute value for NoOfBeneficiary, using the alias name NoOfBeneficiary
     */
    public Number getNoOfBeneficiary() {
        return (Number)getAttributeInternal(NOOFBENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for NoOfBeneficiary
     */
    public void setNoOfBeneficiary(Number value) {
        setAttributeInternal(NOOFBENEFICIARY, value);
    }

    /**Gets the attribute value for PostActEvalRating, using the alias name PostActEvalRating
     */
    public String getPostActEvalRating() {
        return (String)getAttributeInternal(POSTACTEVALRATING);
    }

    /**Sets <code>value</code> as the attribute value for PostActEvalRating
     */
    public void setPostActEvalRating(String value) {
        setAttributeInternal(POSTACTEVALRATING, value);
    }

    /**Gets the attribute value for Remarks, using the alias name Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**Sets <code>value</code> as the attribute value for Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**Gets the attribute value for RequestStatus, using the alias name RequestStatus
     */
    public String getRequestStatus() {
        return (String)getAttributeInternal(REQUESTSTATUS);
    }

    /**Sets <code>value</code> as the attribute value for RequestStatus
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for ItemKey, using the alias name ItemKey
     */
    public String getItemKey() {
        return (String)getAttributeInternal(ITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for ItemKey
     */
    public void setItemKey(String value) {
        setAttributeInternal(ITEMKEY, value);
    }

    /**Gets the attribute value for Status, using the alias name Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for MaleBenefCount, using the alias name MaleBenefCount
     */
    public Number getMaleBenefCount() {
        return (Number)getAttributeInternal(MALEBENEFCOUNT);
    }

    /**Sets <code>value</code> as the attribute value for MaleBenefCount
     */
    public void setMaleBenefCount(Number value) {
        setAttributeInternal(MALEBENEFCOUNT, value);
    }

    /**Gets the attribute value for FemaleBenefCount, using the alias name FemaleBenefCount
     */
    public Number getFemaleBenefCount() {
        return (Number)getAttributeInternal(FEMALEBENEFCOUNT);
    }

    /**Sets <code>value</code> as the attribute value for FemaleBenefCount
     */
    public void setFemaleBenefCount(Number value) {
        setAttributeInternal(FEMALEBENEFCOUNT, value);
    }

    /**Gets the attribute value for ProjectLeader, using the alias name ProjectLeader
     */
    public Number getProjectLeader() {
        return (Number)getAttributeInternal(PROJECTLEADER);
    }

    /**Sets <code>value</code> as the attribute value for ProjectLeader
     */
    public void setProjectLeader(Number value) {
        setAttributeInternal(PROJECTLEADER, value);
    }

    /**Gets the attribute value for RowID, using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SEQUENCENO:
            return getSequenceNo();
        case CONSTITUENTUNIVERSITY:
            return getConstituentUniversity();
        case PROJECTNAME:
            return getProjectName();
        case IMPLEMENTATIONSTARTDATE:
            return getImplementationStartDate();
        case IMPLEMENTATIONENDDATE:
            return getImplementationEndDate();
        case DURATION:
            return getDuration();
        case DURATIONUNIT:
            return getDurationUnit();
        case IMPLEMENTATIONFREQUENCY:
            return getImplementationFrequency();
        case FUNDINGAGENCY:
            return getFundingAgency();
        case COSTOFPARTICIPATION:
            return getCostOfParticipation();
        case UNITOFBENEFICIARY:
            return getUnitOfBeneficiary();
        case NOOFBENEFICIARY:
            return getNoOfBeneficiary();
        case POSTACTEVALRATING:
            return getPostActEvalRating();
        case REMARKS:
            return getRemarks();
        case REQUESTSTATUS:
            return getRequestStatus();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case ITEMKEY:
            return getItemKey();
        case STATUS:
            return getStatus();
        case MALEBENEFCOUNT:
            return getMaleBenefCount();
        case FEMALEBENEFCOUNT:
            return getFemaleBenefCount();
        case PROJECTLEADER:
            return getProjectLeader();
        case ROWID:
            return getRowID();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SEQUENCENO:
            setSequenceNo((Number)value);
            return;
        case CONSTITUENTUNIVERSITY:
            setConstituentUniversity((String)value);
            return;
        case PROJECTNAME:
            setProjectName((String)value);
            return;
        case IMPLEMENTATIONSTARTDATE:
            setImplementationStartDate((Date)value);
            return;
        case IMPLEMENTATIONENDDATE:
            setImplementationEndDate((Date)value);
            return;
        case DURATION:
            setDuration((Number)value);
            return;
        case DURATIONUNIT:
            setDurationUnit((String)value);
            return;
        case IMPLEMENTATIONFREQUENCY:
            setImplementationFrequency((String)value);
            return;
        case FUNDINGAGENCY:
            setFundingAgency((String)value);
            return;
        case COSTOFPARTICIPATION:
            setCostOfParticipation((String)value);
            return;
        case UNITOFBENEFICIARY:
            setUnitOfBeneficiary((String)value);
            return;
        case NOOFBENEFICIARY:
            setNoOfBeneficiary((Number)value);
            return;
        case POSTACTEVALRATING:
            setPostActEvalRating((String)value);
            return;
        case REMARKS:
            setRemarks((String)value);
            return;
        case REQUESTSTATUS:
            setRequestStatus((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case ITEMKEY:
            setItemKey((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case MALEBENEFCOUNT:
            setMaleBenefCount((Number)value);
            return;
        case FEMALEBENEFCOUNT:
            setFemaleBenefCount((Number)value);
            return;
        case PROJECTLEADER:
            setProjectLeader((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);

        if(getSequenceNo() == null){
            OADBTransaction tr = getOADBTransaction();
            setSequenceNo(tr.getSequenceValue("XXUP.XXUP_PER_PS_INST_SEQ"));
        }
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }
}
