DROP TABLE xxup.xxup_per_ps_institutional;
DROP TABLE xxup.xxup_per_ps_institutional_tr;
DROP TABLE xxup.xxup_per_ps_inst_activities;
DROP TABLE xxup.xxup_per_ps_inst_addr;
DROP TABLE xxup.xxup_per_ps_inst_members;
DROP TABLE xxup.xxup_per_ps_inst_office;
DROP TABLE xxup.xxup_per_ps_inst_part_org;
DROP TABLE xxup.xxup_per_ps_inst_subj;
DROP TABLE xxup.xxup_per_ps_inst_obj_cat;
DROP TABLE xxup.xxup_per_ps_inst_benef_org;
DROP TABLE xxup.xxup_per_ps_inst_benef_type;
DROP TABLE xxup.xxup_per_ps_inst_delivery_mode;
DROP TABLE xxup.xxup_per_ps_inst_toa;
DROP TABLE xxup.xxup_per_ps_inst_countries;





--------------------------------------------------------
--  File created - Friday-April-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_ACTION_HISTORY
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_ACTION_HISTORY" 
   (	"ITEM_KEY" VARCHAR2(100 BYTE), 
	"SEQUENCE_NO" VARCHAR2(100 BYTE), 
	"APPROVER_NO" NUMBER, 
	"ACTION" VARCHAR2(30 BYTE), 
	"RECEIVED_DATE" DATE, 
	"ACTION_DATE" DATE, 
	"FROM_EMPLOYEE_ID" NUMBER, 
	"FROM_EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
	"FROM_POSITION_NAME" VARCHAR2(150 BYTE), 
	"TO_EMPLOYEE_ID" NUMBER, 
	"TO_EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
	"TO_POSITION_NAME" VARCHAR2(150 BYTE), 
	"NOTE" VARCHAR2(2000 BYTE), 
	"FROM_ORG_NAME" VARCHAR2(150 BYTE), 
	"TO_ORG_NAME" VARCHAR2(150 BYTE), 
	"TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;

--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_ACTIVITIES
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_ACTIVITIES" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"ACTIVITY" VARCHAR2(200 BYTE), 
	"SELECTED" VARCHAR2(1 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"SELECTED" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_ADDR
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_ADDR" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"ADDRESS" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_BENEF_ORG
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_BENEF_ORG" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"BENEFICIARY_ORGANIZATION" VARCHAR2(240 BYTE), 
	"CONTACT_DETAILS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_BENEF_TYPE
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_BENEF_TYPE" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"TYPE_OF_BENEFICIARY" VARCHAR2(200 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"SELECTED" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_DELIVERY_MODE
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_DELIVERY_MODE" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"DELIVERY_MODE" VARCHAR2(200 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"SELECTED" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_MEMBERS
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_MEMBERS" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"FULL_NAME" VARCHAR2(140 BYTE), 
	"POSITION" VARCHAR2(140 BYTE), 
	"ORGANIZATION" VARCHAR2(140 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"PROJECT_ROLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_OBJ_CAT
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_OBJ_CAT" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"OBJECTIVE_CATEGORY" VARCHAR2(140 BYTE), 
	"SPECIFICS" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_OFFICE
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_OFFICE" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"OFFICE" VARCHAR2(200 BYTE), 
	"TEL_NO" VARCHAR2(50 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_PARTNER_ORG
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_PART_ORG" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(200 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INST_SUBJ
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_SUBJ" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"SUBJECT_AREA_INTEREST" VARCHAR2(140 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"SELECTED" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INSTITUTIONAL
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INSTITUTIONAL" 
   (	"SEQUENCE_NO" NUMBER, 
	"CONSTITUENT_UNIVERSITY" VARCHAR2(30 BYTE), 
	"PROJECT_NAME" VARCHAR2(200 BYTE), 
	"IMPLEMENTATION_START_DATE" DATE, 
	"IMPLEMENTATION_END_DATE" DATE, 
	-- "DURATION_HOURS" VARCHAR2(200 BYTE), 
	"DURATION" NUMBER(5),
	"DURATION_UNIT" VARCHAR2(50 BYTE),
	"IMPLEMENTATION_FREQUENCY" VARCHAR2(50 BYTE), 
	-- "TYPE_OF_ACTIVITY" VARCHAR2(50 BYTE), 
	"FUNDING_AGENCY" VARCHAR2(200 BYTE), 
	"COST_OF_PARTICIPATION" VARCHAR2(200 BYTE), 
	"UNIT_OF_BENEFICIARY" VARCHAR2(200 BYTE), 
	"NO_OF_BENEFICIARY" NUMBER, 
	-- "COUNTRY" VARCHAR2(100 BYTE), 
	"POST_ACT_EVAL_RATING" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"STATUS" VARCHAR2(30 BYTE), 
	"MALE_BENEF_COUNT" NUMBER, 
	"FEMALE_BENEF_COUNT" NUMBER, 
	"PROJECT_LEADER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PS_INSTITUTIONAL_TR
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PS_INSTITUTIONAL_TR" 
   (	"SEQUENCE_NO" NUMBER, 
	"CONSTITUENT_UNIVERSITY" VARCHAR2(30 BYTE), 
	"PROJECT_NAME" VARCHAR2(200 BYTE), 
	"IMPLEMENTATION_START_DATE" DATE, 
	"IMPLEMENTATION_END_DATE" DATE, 
	-- "DURATION_HOURS" VARCHAR2(200 BYTE), 
	"DURATION" NUMBER(5),
	"DURATION_UNIT" VARCHAR2(50 BYTE),
	"IMPLEMENTATION_FREQUENCY" VARCHAR2(50 BYTE), 
	-- "TYPE_OF_ACTIVITY" VARCHAR2(50 BYTE), 
	"FUNDING_AGENCY" VARCHAR2(200 BYTE), 
	"COST_OF_PARTICIPATION" VARCHAR2(200 BYTE), 
	"UNIT_OF_BENEFICIARY" VARCHAR2(200 BYTE), 
	"NO_OF_BENEFICIARY" NUMBER, 
	-- "COUNTRY" VARCHAR2(100 BYTE), 
	"POST_ACT_EVAL_RATING" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"REQUEST_STATUS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"ITEM_KEY" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"MALE_BENEF_COUNT" NUMBER, 
	"FEMALE_BENEF_COUNT" NUMBER, 
	"PROJECT_LEADER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;



  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_TOA" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"TYPE_OF_ACTIVITY" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;


  CREATE TABLE "XXUP"."XXUP_PER_PS_INST_COUNTRIES" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;




--transactional tables

CREATE TABLE xxup.xxup_per_ps_inst_act_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_activities
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_act_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_act_tr FOR xxup.xxup_per_ps_inst_act_tr;



CREATE TABLE xxup.xxup_per_ps_inst_obj_cat_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_obj_cat
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_obj_cat_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_obj_cat_tr FOR xxup.xxup_per_ps_inst_obj_cat_tr;


CREATE TABLE xxup.xxup_per_ps_inst_addr_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_addr
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_addr_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_addr_tr FOR xxup.xxup_per_ps_inst_addr_tr;



CREATE TABLE xxup.xxup_per_ps_inst_benef_org_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_benef_org
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_benef_org_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_benef_org_tr FOR xxup.xxup_per_ps_inst_benef_org_tr;


CREATE TABLE xxup.xxup_per_ps_inst_benef_type_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_benef_type
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_benef_type_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_benef_type_tr FOR xxup.xxup_per_ps_inst_benef_type_tr;


CREATE TABLE xxup.xxup_per_ps_inst_del_mode_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_delivery_mode
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_del_mode_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_del_mode_tr FOR xxup.xxup_per_ps_inst_del_mode_tr;



CREATE TABLE xxup.xxup_per_ps_inst_members_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_members
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_members_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_members_tr FOR xxup.xxup_per_ps_inst_members_tr;


CREATE TABLE xxup.xxup_per_ps_inst_office_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_office
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_office_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_office_tr FOR xxup.xxup_per_ps_inst_office_tr;


CREATE TABLE xxup.xxup_per_ps_inst_part_org_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_part_org
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_part_org_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_part_org_tr FOR xxup.xxup_per_ps_inst_part_org_tr;



CREATE TABLE xxup.xxup_per_ps_inst_subj_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_subj
WHERE 1=2;

ALTER TABLE xxup.xxup_per_ps_inst_subj_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_subj_tr FOR xxup.xxup_per_ps_inst_subj_tr;



CREATE TABLE xxup.xxup_per_ps_inst_toa_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_toa
WHERE 1=2;


ALTER TABLE xxup.xxup_per_ps_inst_toa_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_toa_tr FOR xxup.xxup_per_ps_inst_toa_tr;


CREATE TABLE xxup.xxup_per_ps_inst_countries_tr
AS
SELECT *
FROM xxup.xxup_per_ps_inst_countries;

ALTER TABLE xxup.xxup_per_ps_inst_countries_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_inst_countries_tr FOR xxup.xxup_per_ps_inst_countries_tr;