--------------------------------------------------------
--  File created - Friday-April-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXUP_PER_PUBLIC_SERVICE_ADDR
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PUBLIC_SERVICE_ADDR" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"ADDRESS" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PUBLIC_SERVICE_BENIF
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PUBLIC_SERVICE_BENIF" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"BENEFICIARY_ORGANIZATION" VARCHAR2(240 BYTE), 
	"CONTACT_DETAILS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PUBLIC_SERVICE_CAT
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PUBLIC_SERVICE_CAT" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"OBJECT_CATEGORY" NUMBER, 
	"SPECIFICS" VARCHAR2(240 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PUBLIC_SERVICE_HEADER
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PUBLIC_SERVICE_HEADER" 
   (	"SEQUENCE_NO" NUMBER, 
	"POSITION_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(140 BYTE), 
	"PRIMARY_ROLE" VARCHAR2(140 BYTE), 
	"REQUEST_DATE" DATE, 
	"RESPONDED_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"DURATION_HOURS" NUMBER, 
	-- "TYPE_OF_ACTIVITY" NUMBER, 
	"SOURCE_OF_FUND" VARCHAR2(200 BYTE), 
	"COST_OF_PARTICIPATION" VARCHAR2(200 BYTE), 
	"PARTNER_ORG_OR_INST" VARCHAR2(200 BYTE), 
	"BENEFICIARY_CATEGORY" VARCHAR2(200 BYTE), 
	"UNIT_OF_BENEFICIARY" VARCHAR2(200 BYTE), 
	"NO_OF_BENEFICIARY" NUMBER, 
	-- "COUNTRY" VARCHAR2(100 BYTE), 
	"POST_ACT_EVAL_RATING" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"PROJECT_TYPE" VARCHAR2(50 BYTE), 
	"TYPE_OF_BENEFICIARY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  DDL for Table XXUP_PER_PUBLIC_SERVICE_SUBJ
--------------------------------------------------------

  CREATE TABLE "XXUP"."XXUP_PER_PUBLIC_SERVICE_SUBJ" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"SUBJECT_AREA_INTEREST" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"SELECTED" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;



  CREATE TABLE "XXUP"."XXUP_PER_PS_HEADER_TR" 
   (	"SEQUENCE_NO" NUMBER, 
	"POSITION_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(140 BYTE), 
	"PRIMARY_ROLE" VARCHAR2(140 BYTE), 
	"REQUEST_DATE" DATE, 
	"RESPONDED_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"DURATION_HOURS" NUMBER, 
	-- "TYPE_OF_ACTIVITY" NUMBER, 
	"SOURCE_OF_FUND" VARCHAR2(200 BYTE), 
	"COST_OF_PARTICIPATION" VARCHAR2(200 BYTE), 
	"PARTNER_ORG_OR_INST" VARCHAR2(200 BYTE), 
	"BENEFICIARY_CATEGORY" VARCHAR2(200 BYTE), 
	"UNIT_OF_BENEFICIARY" VARCHAR2(200 BYTE), 
	"NO_OF_BENEFICIARY" NUMBER, 
	-- "COUNTRY" VARCHAR2(100 BYTE), 
	"POST_ACT_EVAL_RATING" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"REQUEST_STATUS" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"PROJECT_TYPE" VARCHAR2(50 BYTE), 
	"TYPE_OF_BENEFICIARY" VARCHAR2(100 BYTE), 
	"ITEM_KEY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;

  CREATE TABLE "XXUP"."XXUP_PER_PS_COUNTRIES" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;




  CREATE TABLE "XXUP"."XXUP_PER_PS_TYPE_OF_ACTIVITIES" 
   (	"SEQUENCE_NO" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"TYPE_OF_ACTIVITY" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(140 BYTE), 
	"ATTRIBUTE2" VARCHAR2(140 BYTE), 
	"ATTRIBUTE3" VARCHAR2(140 BYTE), 
	"ATTRIBUTE4" VARCHAR2(140 BYTE), 
	"ATTRIBUTE5" VARCHAR2(140 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "APPS_TS_TX_DATA" ;


--transactional tables

CREATE TABLE xxup.xxup_per_ps_cat_tr
AS
SELECT *
FROM xxup.xxup_per_public_service_cat;

ALTER TABLE xxup.xxup_per_ps_cat_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_cat_tr FOR xxup.xxup_per_ps_cat_tr;


CREATE TABLE xxup.xxup_per_ps_addr_tr
AS
SELECT *
FROM xxup.xxup_per_public_service_addr;

ALTER TABLE xxup.xxup_per_ps_addr_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_addr_tr FOR xxup.xxup_per_ps_addr_tr;



CREATE TABLE xxup.xxup_per_ps_benif_tr
AS
SELECT *
FROM xxup.xxup_per_public_service_benif;

ALTER TABLE xxup.xxup_per_ps_benif_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_benif_tr FOR xxup.xxup_per_ps_benif_tr;


CREATE TABLE xxup.xxup_per_ps_subj_tr
AS
SELECT *
FROM xxup.xxup_per_public_service_subj;

ALTER TABLE xxup.xxup_per_ps_subj_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_subj_tr FOR xxup.xxup_per_ps_subj_tr;



CREATE TABLE xxup.xxup_per_ps_toa_tr
AS
SELECT *
FROM xxup.xxup_per_ps_type_of_activities;

ALTER TABLE xxup.xxup_per_ps_toa_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_toa_tr FOR xxup.xxup_per_ps_toa_tr;


CREATE TABLE xxup.xxup_per_ps_countries_tr
AS
SELECT *
FROM xxup.xxup_per_ps_countries;

ALTER TABLE xxup.xxup_per_ps_countries_tr
    ADD item_key VARCHAR2(20);
    
CREATE OR REPLACE SYNONYM xxup_per_ps_countries_tr FOR xxup.xxup_per_ps_countries_tr;