/*Public Service*/
CREATE OR REPLACE SYNONYM XXUP_PER_PUBLIC_SERVICE_ADDR FOR XXUP.XXUP_PER_PUBLIC_SERVICE_ADDR;
CREATE OR REPLACE SYNONYM XXUP_PER_PUBLIC_SERVICE_BENIF FOR XXUP.XXUP_PER_PUBLIC_SERVICE_BENIF;
CREATE OR REPLACE SYNONYM XXUP_PER_PUBLIC_SERVICE_CAT FOR XXUP.XXUP_PER_PUBLIC_SERVICE_CAT;
CREATE OR REPLACE SYNONYM XXUP_PER_PUBLIC_SERVICE_HEADER FOR XXUP.XXUP_PER_PUBLIC_SERVICE_HEADER;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_HEADER_TR FOR XXUP.XXUP_PER_PS_HEADER_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PUBLIC_SERVICE_SUBJ FOR XXUP.XXUP_PER_PUBLIC_SERVICE_SUBJ;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_HEADER_TR FOR XXUP.XXUP_PER_PS_HEADER_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_TYPE_OF_ACTIVITIES FOR XXUP.XXUP_PER_PS_TYPE_OF_ACTIVITIES;   
CREATE OR REPLACE SYNONYM XXUP_PER_PS_COUNTRIES FOR XXUP.XXUP_PER_PS_COUNTRIES;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_BENEF_TYPE FOR XXUP.XXUP_PER_PS_BENEF_TYPE;


/*PS-TR*/
CREATE OR REPLACE SYNONYM XXUP_PER_PS_HEADER_TR FOR XXUP.XXUP_PER_PS_HEADER_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_ADDR_TR FOR XXUP.XXUP_PER_PS_ADDR_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_BENIF_TR FOR XXUP.XXUP_PER_PS_BENIF_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_CAT_TR FOR XXUP.XXUP_PER_PS_CAT_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_COUNTRIES FOR XXUP.XXUP_PER_PS_COUNTRIES;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_COUNTRIES_TR FOR XXUP.XXUP_PER_PS_COUNTRIES_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_SUBJ_TR FOR XXUP.XXUP_PER_PS_SUBJ_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_TOA_TR FOR XXUP.XXUP_PER_PS_TOA_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_BENEF_TYPE_TR FOR XXUP.XXUP_PER_PS_BENEF_TYPE_TR;


/*Institutional*/
CREATE OR REPLACE SYNONYM XXUP_PER_PS_ACTION_HISTORY FOR XXUP.XXUP_PER_PS_ACTION_HISTORY;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INSTITUTIONAL FOR XXUP.XXUP_PER_PS_INSTITUTIONAL;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_ACTIVITIES FOR XXUP.XXUP_PER_PS_INST_ACTIVITIES;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_ADDR FOR XXUP.XXUP_PER_PS_INST_ADDR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_BENEF_ORG FOR XXUP.XXUP_PER_PS_INST_BENEF_ORG;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_BENEF_TYPE FOR XXUP.XXUP_PER_PS_INST_BENEF_TYPE;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_DELIVERY_MODE FOR XXUP.XXUP_PER_PS_INST_DELIVERY_MODE;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_MEMBERS FOR XXUP.XXUP_PER_PS_INST_MEMBERS;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_OBJ_CAT FOR XXUP.XXUP_PER_PS_INST_OBJ_CAT;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_OFFICE FOR XXUP.XXUP_PER_PS_INST_OFFICE;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_PART_ORG FOR XXUP.XXUP_PER_PS_INST_PART_ORG;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_SUBJ FOR XXUP.XXUP_PER_PS_INST_SUBJ;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_TOA FOR XXUP.XXUP_PER_PS_INST_TOA;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_TOA FOR XXUP.XXUP_PER_PS_INST_COUNTRIES;




/*PSINST-TR*/
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INSTITUTIONAL_TR FOR XXUP.XXUP_PER_PS_INSTITUTIONAL_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_ACT_TR FOR XXUP.XXUP_PER_PS_INST_ACT_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_ADDR_TR FOR XXUP.XXUP_PER_PS_INST_ADDR_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_BENEF_ORG_TR FOR XXUP.XXUP_PER_PS_INST_BENEF_ORG_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_BENEF_TYPE_TR FOR XXUP.XXUP_PER_PS_INST_BENEF_TYPE_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_COUNTRIES FOR XXUP.XXUP_PER_PS_INST_COUNTRIES;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_COUNTRIES_TR FOR XXUP.XXUP_PER_PS_INST_COUNTRIES_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_DEL_MODE_TR FOR XXUP.XXUP_PER_PS_INST_DEL_MODE_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_MEMBERS_TR FOR XXUP.XXUP_PER_PS_INST_MEMBERS_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_OBJ_CAT_TR FOR XXUP.XXUP_PER_PS_INST_OBJ_CAT_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_OFFICE_TR FOR XXUP.XXUP_PER_PS_INST_OFFICE_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_PART_ORG_TR FOR XXUP.XXUP_PER_PS_INST_PART_ORG_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_SUBJ_TR FOR XXUP.XXUP_PER_PS_INST_SUBJ_TR;
CREATE OR REPLACE SYNONYM XXUP_PER_PS_INST_TOA_TR FOR XXUP.XXUP_PER_PS_INST_TOA_TR;